added swap

diff --git a/cachyos/install b/cachyos/install
--- a/cachyos/install
+++ b/cachyos/install
@@ -4,7 +4,7 @@ set -e
 
 # Ensure /mnt is unmounted
 if lsblk | grep "/mnt$" >/dev/null 2>&1; then
-    umount -q -A --recursive /mnt
+	umount -q -A --recursive /mnt
 fi
 
 # Print available disks
@@ -17,32 +17,32 @@ read -r -p "Enter Full Name: " fullname
 read -r -p "Enter computer name: " hostname
 
 while :; do
-    read -s -r -p "Enter user password: " password
-    echo
-    read -s -r -p "Enter user password again: " password2
-    echo
-    [[ $password != "$password2" ]] || break
-    echo "error try again"
+	read -s -r -p "Enter user password: " password
+	echo
+	read -s -r -p "Enter user password again: " password2
+	echo
+	[[ $password != "$password2" ]] || break
+	echo "error try again"
 done
 
 while :; do
-    echo
-    read -s -r -p "Enter root password: " rootPassword
-    echo
-    read -s -r -p "Enter root password: " rootPassword2
-    echo
-    [[ $rootPassword != "$rootPassword2" ]] || break
-    echo "error try again"
+	echo
+	read -s -r -p "Enter root password: " rootPassword
+	echo
+	read -s -r -p "Enter root password: " rootPassword2
+	echo
+	[[ $rootPassword != "$rootPassword2" ]] || break
+	echo "error try again"
 done
 
 while :; do
-    echo
-    read -s -r -p "Enter luks password: " luksPassword
-    echo
-    read -s -r -p "Enter luks password: " luksPassword2
-    echo
-    [[ $luksPassword != "$luksPassword2" ]] || break
-    echo "error try again"
+	echo
+	read -s -r -p "Enter luks password: " luksPassword
+	echo
+	read -s -r -p "Enter luks password: " luksPassword2
+	echo
+	[[ $luksPassword != "$luksPassword2" ]] || break
+	echo "error try again"
 done
 
 clear
@@ -65,9 +65,9 @@ pacman -Sy archlinux-keyring debugedit --noconfirm
 pacman-key --recv-keys F3B607488DB35A47 --keyserver keyserver.ubuntu.com
 pacman-key --lsign-key F3B607488DB35A47
 pacman -U --noconfirm 'https://mirror.cachyos.org/repo/x86_64/cachyos/cachyos-keyring-20240331-1-any.pkg.tar.zst' \
-    'https://mirror.cachyos.org/repo/x86_64/cachyos/cachyos-mirrorlist-18-1-any.pkg.tar.zst' \
-    'https://mirror.cachyos.org/repo/x86_64/cachyos/cachyos-v3-mirrorlist-18-1-any.pkg.tar.zst' \
-    'https://mirror.cachyos.org/repo/x86_64/cachyos/pacman-6.1.0-7-x86_64.pkg.tar.zst'
+	'https://mirror.cachyos.org/repo/x86_64/cachyos/cachyos-mirrorlist-18-1-any.pkg.tar.zst' \
+	'https://mirror.cachyos.org/repo/x86_64/cachyos/cachyos-v3-mirrorlist-18-1-any.pkg.tar.zst' \
+	'https://mirror.cachyos.org/repo/x86_64/cachyos/pacman-6.1.0-7-x86_64.pkg.tar.zst'
 
 sed -i '/# after the header, and they will be used before the default mirrors./a\
 \
@@ -93,12 +93,12 @@ sgdisk --clear "${device}" --new 1::-512MiB "${device}" --new 2::0 --typecode 2:
 sgdisk --change-name=1:primary --change-name=2:ESP "${device}"
 
 if [[ $disk == *"nvme"* ]]; then
-    part_root=${device}p1
-    part_boot=${device}p2
+	part_root=${device}p1
+	part_boot=${device}p2
 else
-    part_root=${device}1
-    part_boot=${device}2
-    mkfs.vfat -n "EFI" -F 32 "${part_boot}"
+	part_root=${device}1
+	part_boot=${device}2
+	mkfs.vfat -n "EFI" -F 32 "${part_boot}"
 fi
 
 mkfs.vfat -n "EFI" -F 32 "${part_boot}"
@@ -116,6 +116,9 @@ btrfs subvolume create /mnt/@var
 btrfs subvolume create /mnt/@home
 btrfs subvolume create /mnt/@snapshots
 
+btrfs subvolume create /mnt/swap
+btrfs filesystem mkswapfile --size 12g --uuid clear /mnt/swap/swapfile
+
 umount /mnt
 mount -o noatime,nodiratime,compress=zstd,subvol=@ ${part_root_install} /mnt
 mkdir /mnt/{var,home,.snapshots,boot}
@@ -131,12 +134,12 @@ pacstrap /mnt btrfs-progs
 # Determine intel or amd
 ucode=""
 if lscpu | grep "Model name:" | grep AMD >/dev/null 2>&1; then
-    ucode="amd-ucode"
+	ucode="amd-ucode"
 elif lscpu | grep "Model name:" | grep Intel >/dev/null 2>&1; then
-    ucode="intel-ucode"
+	ucode="intel-ucode"
 else
-    echo "Unkown CPU"
-    exit 1
+	echo "Unkown CPU"
+	exit 1
 fi
 
 ## Install Arch
@@ -152,6 +155,12 @@ sed -i "s/'default' 'fallback'/'default'/" /mnt/etc/mkinitcpio.d/linux-*.preset
 
 ## Setup fstab
 genfstab -U /mnt >>/mnt/etc/fstab
+
+cat <<EOF >>/mnt/etc/fstab
+
+# Swap
+/swap/swapfile none swap defaults 0 0
+EOF
 
 ## Copy post install to new root
 cp /etc/pacman.conf /mnt/etc/pacman.conf -f
